name: Deploy to AWS EC2
on:
  push:
    branches: [ "week5" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 3.16.13.9
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script_stop: true
        command_timeout: 1m
        script: |
          # Quick process cleanup
          pkill -f "python app.py" || true
          pkill -f "streamlit run frontend.py" || true
          
          # Deploy applications
          cd /home/${{ secrets.EC2_USERNAME }}/aiops
          git fetch origin week5
          git reset --hard origin/week5
          
          cd backend
          source venv/bin/activate
          nohup python app.py > /dev/null 2>&1 &
          deactivate
          
          cd ../frontend
          source venv/bin/activate
          nohup streamlit run frontend.py --server.address 0.0.0.0 --server.port 8501 > /dev/null 2>&1 &
          deactivate
